# 配置文件

DAILY_TIME: "7:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-09-01"纪念日
CITY: "石家庄"

BIRTHDAY:
  - "10-04

APP_ID: "wx0b26083870774359"
APP_SECRET: "c4bd55a2663952b8d54a81d4f2d8fc32"

USER_ID: 
  - "ohCua5sulBovoKkLNaoLwRLQyRy4"
TEMPLATE_ID: "微信公众平台的 TEMPLATE ID"
